<?php
$configs['app']=[
    'service'=>[
        HtmlHelper::class
    ],
    'routesMiddleWare'=>[
         'san-pham'=>AuthMiddleWare::class
    ],
    'globalMiddleWare'=>[
        ParamsMiddleWare::class
    ],
    'boot'=>[
        AddServiceProvider::class
    ]
];
?>